CREATE TABLE iso_codes(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(75) NOT NULL,
	alpha2 VARCHAR(2) NOT NULL,
	alpha3 VARCHAR(3) NOT NULL,
	nbr INT NOT NULL,
	CONSTRAINT pk_ISOCODES PRIMARY KEY(id)
);

INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('AALAND ISLANDS','AX','ALA',248);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('AFGHANISTAN','AF','AFG',4);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ALBANIA','AL','ALB',8);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ALGERIA','DZ','DZA',12);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('AMERICAN SAMOA','AS','ASM',16);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ANDORRA','AD','AND',20);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ANGOLA','AO','AGO',24);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ANGUILLA','AI','AIA',660);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ANTARCTICA','AQ','ATA',10);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ANTIGUA AND BARBUDA','AG','ATG',28);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ARGENTINA','AR','ARG',32);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ARMENIA','AM','ARM',51);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ARUBA','AW','ABW',533);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('AUSTRALIA','AU','AUS',36);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('AUSTRIA','AT','AUT',40);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('AZERBAIJAN','AZ','AZE',31);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BAHAMAS','BS','BHS',44);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BAHRAIN','BH','BHR',48);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BANGLADESH','BD','BGD',50);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BARBADOS','BB','BRB',52);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BELARUS','BY','BLR',112);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BELGIUM','BE','BEL',56);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BELIZE','BZ','BLZ',84);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BENIN','BJ','BEN',204);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BERMUDA','BM','BMU',60);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BHUTAN','BT','BTN',64);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BOLIVIA','BO','BOL',68);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BOSNIA AND HERZEGOWINA','BA','BIH',70);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BOTSWANA','BW','BWA',72);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BOUVET ISLAND','BV','BVT',74);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BRAZIL','BR','BRA',76);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BRITISH INDIAN OCEAN TERRITORY','IO','IOT',86);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BRUNEI DARUSSALAM','BN','BRN',96);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BULGARIA','BG','BGR',100);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BURKINA FASO','BF','BFA',854);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('BURUNDI','BI','BDI',108);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('CAMBODIA','KH','KHM',116);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('CAMEROON','CM','CMR',120);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('CANADA','CA','CAN',124);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('CAPE VERDE','CV','CPV',132);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('CAYMAN ISLANDS','KY','CYM',136);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('CENTRAL AFRICAN REPUBLIC','CF','CAF',140);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('CHAD','TD','TCD',148);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('CHILE','CL','CHL',152);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('CHINA','CN','CHN',156);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('CHRISTMAS ISLAND','CX','CXR',162);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('COCOS (KEELING) ISLANDS','CC','CCK',166);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('COLOMBIA','CO','COL',170);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('COMOROS','KM','COM',174);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('DEMOCRATIC REPUBLIC OF CONGO','CD','COD',180);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('REPUBLIC OF CONGO','CG','COG',178);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('COOK ISLANDS','CK','COK',184);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('COSTA RICA','CR','CRI',188);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('COTE D\'IVOIRE','CI','CIV',384);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('CROATIA','HR','HRV',191);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('CUBA','CU','CUB',192);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('CYPRUS','CY','CYP',196);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('CZECH REPUBLIC','CZ','CZE',203);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('DENMARK','DK','DNK',208);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('DJIBOUTI','DJ','DJI',262);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('DOMINICA','DM','DMA',212);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('DOMINICAN REPUBLIC','DO','DOM',214);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ECUADOR','EC','ECU',218);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('EGYPT','EG','EGY',818);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('EL SALVADOR','SV','SLV',222);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('EQUATORIAL GUINEA','GQ','GNQ',226);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ERITREA','ER','ERI',232);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ESTONIA','EE','EST',233);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ETHIOPIA','ET','ETH',231);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('FALKLAND ISLANDS (MALVINAS)','FK','FLK',238);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('FAROE ISLANDS','FO','FRO',234);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('FIJI','FJ','FJI',242);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('FINLAND','FI','FIN',246);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('FRANCE','FR','FRA',250);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('FRENCH GUIANA','GF','GUF',254);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('FRENCH POLYNESIA','PF','PYF',258);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('FRENCH SOUTHERN TERRITORIES','TF','ATF',260);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('GABON','GA','GAB',266);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('GAMBIA','GM','GMB',270);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('GEORGIA','GE','GEO',268);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('GERMANY','DE','DEU',276);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('GHANA','GH','GHA',288);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('GIBRALTAR','GI','GIB',292);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('GREECE','GR','GRC',300);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('GREENLAND','GL','GRL',304);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('GRENADA','GD','GRD',308);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('GUADELOUPE','GP','GLP',312);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('GUAM','GU','GUM',316);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('GUATEMALA','GT','GTM',320);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('GUINEA','GN','GIN',324);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('GUINEA-BISSAU','GW','GNB',624);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('GUYANA','GY','GUY',328);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('HAITI','HT','HTI',332);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('HEARD AND MC DONALD ISLANDS','HM','HMD',334);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('HONDURAS','HN','HND',340);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('HONG KONG','HK','HKG',344);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('HUNGARY','HU','HUN',348);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ICELAND','IS','ISL',352);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('INDIA','IN','IND',356);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('INDONESIA','ID','IDN',360);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('IRAN','IR','IRN',364);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('IRAQ','IQ','IRQ',368);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('IRELAND','IE','IRL',372);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ISRAEL','IL','ISR',376);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ITALY','IT','ITA',380);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('JAMAICA','JM','JAM',388);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('JAPAN','JP','JPN',392);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('JORDAN','JO','JOR',400);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('KAZAKHSTAN','KZ','KAZ',398);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('KENYA','KE','KEN',404);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('KIRIBATI','KI','KIR',296);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('DEMOCRATIC PEOPLE\'S REPUBLIC OF KOREA','KP','PRK',408);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('REPUBLIC OF KOREA','KR','KOR',410);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('KUWAIT','KW','KWT',414);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('KYRGYZSTAN','KG','KGZ',417);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('LAO PEOPLE\'S DEMOCRATIC REPUBLIC','LA','LAO',418);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('LATVIA','LV','LVA',428);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('LEBANON','LB','LBN',422);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('LESOTHO','LS','LSO',426);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('LIBERIA','LR','LBR',430);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('LIBYAN ARAB JAMAHIRIYA','LY','LBY',434);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('LIECHTENSTEIN','LI','LIE',438);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('LITHUANIA','LT','LTU',440);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('LUXEMBOURG','LU','LUX',442);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MACAU','MO','MAC',446);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('THE FORMER YUGOSLAV REPUBLIC OF MACEDONIA','MK','MKD',807);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MADAGASCAR','MG','MDG',450);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MALAWI','MW','MWI',454);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MALAYSIA','MY','MYS',458);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MALDIVES','MV','MDV',462);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MALI','ML','MLI',466);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MALTA','MT','MLT',470);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MARSHALL ISLANDS','MH','MHL',584);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MARTINIQUE','MQ','MTQ',474);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MAURITANIA','MR','MRT',478);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MAURITIUS','MU','MUS',480);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MAYOTTE','YT','MYT',175);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MEXICO','MX','MEX',484);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('FEDERATED STATES OF MICRONESIA','FM','FSM',583);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('REPUBLIC OF MOLDOVA','MD','MDA',498);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MONACO','MC','MCO',492);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MONGOLIA','MN','MNG',496);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MONTSERRAT','MS','MSR',500);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MOROCCO','MA','MAR',504);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MOZAMBIQUE','MZ','MOZ',508);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('MYANMAR','MM','MMR',104);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('NAMIBIA','NA','NAM',516);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('NAURU','NR','NRU',520);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('NEPAL','NP','NPL',524);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('NETHERLANDS','NL','NLD',528);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('NETHERLANDS ANTILLES','AN','ANT',530);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('NEW CALEDONIA','NC','NCL',540);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('NEW ZEALAND','NZ','NZL',554);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('NICARAGUA','NI','NIC',558);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('NIGER','NE','NER',562);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('NIGERIA','NG','NGA',566);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('NIUE','NU','NIU',570);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('NORFOLK ISLAND','NF','NFK',574);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('NORTHERN MARIANA ISLANDS','MP','MNP',580);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('NORWAY','NO','NOR',578);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('OMAN','OM','OMN',512);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('PAKISTAN','PK','PAK',586);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('PALAU','PW','PLW',585);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('PALESTINIAN TERRITORY','PS','PSE',275);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('PANAMA','PA','PAN',591);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('PAPUA NEW GUINEA','PG','PNG',598);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('PARAGUAY','PY','PRY',600);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('PERU','PE','PER',604);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('PHILIPPINES','PH','PHL',608);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('PITCAIRN','PN','PCN',612);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('POLAND','PL','POL',616);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('PORTUGAL','PT','PRT',620);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('PUERTO RICO','PR','PRI',630);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('QATAR','QA','QAT',634);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('REUNION','RE','REU',638);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ROMANIA','RO','ROU',642);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('RUSSIAN FEDERATION','RU','RUS',643);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('RWANDA','RW','RWA',646);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SAINT HELENA','SH','SHN',654);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SAINT KITTS AND NEVIS','KN','KNA',659);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SAINT LUCIA','LC','LCA',662);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SAINT PIERRE AND MIQUELON','PM','SPM',666);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SAINT VINCENT AND THE GRENADINES','VC','VCT',670);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SAMOA','WS','WSM',882);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SAN MARINO','SM','SMR',674);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SAO TOME AND PRINCIPE','ST','STP',678);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SAUDI ARABIA','SA','SAU',682);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SENEGAL','SN','SEN',686);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SERBIA AND MONTENEGRO','CS','SCG',891);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SEYCHELLES','SC','SYC',690);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SIERRA LEONE','SL','SLE',694);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SINGAPORE','SG','SGP',702);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SLOVAKIA','SK','SVK',703);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SLOVENIA','SI','SVN',705);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SOLOMON ISLANDS','SB','SLB',90);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SOMALIA','SO','SOM',706);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SOUTH AFRICA','ZA','ZAF',710);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','GS','SGS',239);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SPAIN','ES','ESP',724);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SRI LANKA','LK','LKA',144);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SUDAN','SD','SDN',736);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SURINAME','SR','SUR',740);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SVALBARD AND JAN MAYEN ISLANDS','SJ','SJM',744);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SWAZILAND','SZ','SWZ',748);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SWEDEN','SE','SWE',752);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SWITZERLAND','CH','CHE',756);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('SYRIAN ARAB REPUBLIC','SY','SYR',760);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('TAIWAN','TW','TWN',158);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('TAJIKISTAN','TJ','TJK',762);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('UNITED REPUBLIC OF TANZANIA','TZ','TZA',834);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('THAILAND','TH','THA',764);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('TIMOR-LESTE','TL','TLS',626);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('TOGO','TG','TGO',768);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('TOKELAU','TK','TKL',772);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('TONGA','TO','TON',776);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('TRINIDAD AND TOBAGO','TT','TTO',780);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('TUNISIA','TN','TUN',788);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('TURKEY','TR','TUR',792);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('TURKMENISTAN','TM','TKM',795);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('TURKS AND CAICOS ISLANDS','TC','TCA',796);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('TUVALU','TV','TUV',798);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('UGANDA','UG','UGA',800);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('UKRAINE','UA','UKR',804);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('UNITED ARAB EMIRATES','AE','ARE',784);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('UNITED KINGDOM','GB','GBR',826);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('UNITED STATES','US','USA',840);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('UNITED STATES MINOR OUTLYING ISLANDS','UM','UMI',581);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('URUGUAY','UY','URY',858);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('UZBEKISTAN','UZ','UZB',860);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('VANUATU','VU','VUT',548);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('VATICAN CITY STATE (HOLY SEE)','VA','VAT',336);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('VENEZUELA','VE','VEN',862);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('VIET NAM','VN','VNM',704);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('VIRGIN ISLANDS (BRITISH)','VG','VGB',92);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('VIRGIN ISLANDS (U.S.)','VI','VIR',850);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('WALLIS AND FUTUNA ISLANDS','WF','WLF',876);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('WESTERN SAHARA','EH','ESH',732);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('YEMEN','YE','YEM',887);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ZAMBIA','ZM','ZMB',894);
INSERT INTO iso_codes(name,alpha2,alpha3,nbr) VALUES ('ZIMBABWE','ZW','ZWE',716);
