CREATE TABLE iso_codes(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	alpha2 VARCHAR(2) NOT NULL,
	CONSTRAINT pk_ISOCODES PRIMARY KEY(id)
);

INSERT INTO iso_codes(name,alpha2) VALUES ('AFGHANISTAN','AF');
INSERT INTO iso_codes(name,alpha2) VALUES ('Ã?LAND ISLANDS','AX');
INSERT INTO iso_codes(name,alpha2) VALUES ('ALBANIA','AL');
INSERT INTO iso_codes(name,alpha2) VALUES ('ALGERIA','DZ');
INSERT INTO iso_codes(name,alpha2) VALUES ('AMERICAN SAMOA','AS');
INSERT INTO iso_codes(name,alpha2) VALUES ('ANDORRA','AD');
INSERT INTO iso_codes(name,alpha2) VALUES ('ANGOLA','AO');
INSERT INTO iso_codes(name,alpha2) VALUES ('ANGUILLA','AI');
INSERT INTO iso_codes(name,alpha2) VALUES ('ANTARCTICA','AQ');
INSERT INTO iso_codes(name,alpha2) VALUES ('ANTIGUA AND BARBUDA','AG');
INSERT INTO iso_codes(name,alpha2) VALUES ('ARGENTINA','AR');
INSERT INTO iso_codes(name,alpha2) VALUES ('ARMENIA','AM');
INSERT INTO iso_codes(name,alpha2) VALUES ('ARUBA','AW');
INSERT INTO iso_codes(name,alpha2) VALUES ('AUSTRALIA','AU');
INSERT INTO iso_codes(name,alpha2) VALUES ('AUSTRIA','AT');
INSERT INTO iso_codes(name,alpha2) VALUES ('AZERBAIJAN','AZ');
INSERT INTO iso_codes(name,alpha2) VALUES ('BAHAMAS','BS');
INSERT INTO iso_codes(name,alpha2) VALUES ('BAHRAIN','BH');
INSERT INTO iso_codes(name,alpha2) VALUES ('BANGLADESH','BD');
INSERT INTO iso_codes(name,alpha2) VALUES ('BARBADOS','BB');
INSERT INTO iso_codes(name,alpha2) VALUES ('BELARUS','BY');
INSERT INTO iso_codes(name,alpha2) VALUES ('BELGIUM','BE');
INSERT INTO iso_codes(name,alpha2) VALUES ('BELIZE','BZ');
INSERT INTO iso_codes(name,alpha2) VALUES ('BENIN','BJ');
INSERT INTO iso_codes(name,alpha2) VALUES ('BERMUDA','BM');
INSERT INTO iso_codes(name,alpha2) VALUES ('BHUTAN','BT');
INSERT INTO iso_codes(name,alpha2) VALUES ('BOLIVIA, PLURINATIONAL STATE OF','BO');
INSERT INTO iso_codes(name,alpha2) VALUES ('BONAIRE, SINT EUSTATIUS AND SABA','BQ');
INSERT INTO iso_codes(name,alpha2) VALUES ('BOSNIA AND HERZEGOVINA','BA');
INSERT INTO iso_codes(name,alpha2) VALUES ('BOTSWANA','BW');
INSERT INTO iso_codes(name,alpha2) VALUES ('BOUVET ISLAND','BV');
INSERT INTO iso_codes(name,alpha2) VALUES ('BRAZIL','BR');
INSERT INTO iso_codes(name,alpha2) VALUES ('BRITISH INDIAN OCEAN TERRITORY','IO');
INSERT INTO iso_codes(name,alpha2) VALUES ('BRUNEI DARUSSALAM','BN');
INSERT INTO iso_codes(name,alpha2) VALUES ('BULGARIA','BG');
INSERT INTO iso_codes(name,alpha2) VALUES ('BURKINA FASO','BF');
INSERT INTO iso_codes(name,alpha2) VALUES ('BURUNDI','BI');
INSERT INTO iso_codes(name,alpha2) VALUES ('CAMBODIA','KH');
INSERT INTO iso_codes(name,alpha2) VALUES ('CAMEROON','CM');
INSERT INTO iso_codes(name,alpha2) VALUES ('CANADA','CA');
INSERT INTO iso_codes(name,alpha2) VALUES ('CAPE VERDE','CV');
INSERT INTO iso_codes(name,alpha2) VALUES ('CAYMAN ISLANDS','KY');
INSERT INTO iso_codes(name,alpha2) VALUES ('CENTRAL AFRICAN REPUBLIC','CF');
INSERT INTO iso_codes(name,alpha2) VALUES ('CHAD','TD');
INSERT INTO iso_codes(name,alpha2) VALUES ('CHILE','CL');
INSERT INTO iso_codes(name,alpha2) VALUES ('CHINA','CN');
INSERT INTO iso_codes(name,alpha2) VALUES ('CHRISTMAS ISLAND','CX');
INSERT INTO iso_codes(name,alpha2) VALUES ('COCOS (KEELING) ISLANDS','CC');
INSERT INTO iso_codes(name,alpha2) VALUES ('COLOMBIA','CO');
INSERT INTO iso_codes(name,alpha2) VALUES ('COMOROS','KM');
INSERT INTO iso_codes(name,alpha2) VALUES ('CONGO','CG');
INSERT INTO iso_codes(name,alpha2) VALUES ('CONGO, THE DEMOCRATIC REPUBLIC OF THE','CD');
INSERT INTO iso_codes(name,alpha2) VALUES ('COOK ISLANDS','CK');
INSERT INTO iso_codes(name,alpha2) VALUES ('COSTA RICA','CR');
INSERT INTO iso_codes(name,alpha2) VALUES ('CÃ?TE D\'IVOIRE','CI');
INSERT INTO iso_codes(name,alpha2) VALUES ('CROATIA','HR');
INSERT INTO iso_codes(name,alpha2) VALUES ('CUBA','CU');
INSERT INTO iso_codes(name,alpha2) VALUES ('CURAÃ?AO','CW');
INSERT INTO iso_codes(name,alpha2) VALUES ('CYPRUS','CY');
INSERT INTO iso_codes(name,alpha2) VALUES ('CZECH REPUBLIC','CZ');
INSERT INTO iso_codes(name,alpha2) VALUES ('DENMARK','DK');
INSERT INTO iso_codes(name,alpha2) VALUES ('DJIBOUTI','DJ');
INSERT INTO iso_codes(name,alpha2) VALUES ('DOMINICA','DM');
INSERT INTO iso_codes(name,alpha2) VALUES ('DOMINICAN REPUBLIC','DO');
INSERT INTO iso_codes(name,alpha2) VALUES ('ECUADOR','EC');
INSERT INTO iso_codes(name,alpha2) VALUES ('EGYPT','EG');
INSERT INTO iso_codes(name,alpha2) VALUES ('EL SALVADOR','SV');
INSERT INTO iso_codes(name,alpha2) VALUES ('EQUATORIAL GUINEA','GQ');
INSERT INTO iso_codes(name,alpha2) VALUES ('ERITREA','ER');
INSERT INTO iso_codes(name,alpha2) VALUES ('ESTONIA','EE');
INSERT INTO iso_codes(name,alpha2) VALUES ('ETHIOPIA','ET');
INSERT INTO iso_codes(name,alpha2) VALUES ('FALKLAND ISLANDS (MALVINAS)','FK');
INSERT INTO iso_codes(name,alpha2) VALUES ('FAROE ISLANDS','FO');
INSERT INTO iso_codes(name,alpha2) VALUES ('FIJI','FJ');
INSERT INTO iso_codes(name,alpha2) VALUES ('FINLAND','FI');
INSERT INTO iso_codes(name,alpha2) VALUES ('FRANCE','FR');
INSERT INTO iso_codes(name,alpha2) VALUES ('FRENCH GUIANA','GF');
INSERT INTO iso_codes(name,alpha2) VALUES ('FRENCH POLYNESIA','PF');
INSERT INTO iso_codes(name,alpha2) VALUES ('FRENCH SOUTHERN TERRITORIES','TF');
INSERT INTO iso_codes(name,alpha2) VALUES ('GABON','GA');
INSERT INTO iso_codes(name,alpha2) VALUES ('GAMBIA','GM');
INSERT INTO iso_codes(name,alpha2) VALUES ('GEORGIA','GE');
INSERT INTO iso_codes(name,alpha2) VALUES ('GERMANY','DE');
INSERT INTO iso_codes(name,alpha2) VALUES ('GHANA','GH');
INSERT INTO iso_codes(name,alpha2) VALUES ('GIBRALTAR','GI');
INSERT INTO iso_codes(name,alpha2) VALUES ('GREECE','GR');
INSERT INTO iso_codes(name,alpha2) VALUES ('GREENLAND','GL');
INSERT INTO iso_codes(name,alpha2) VALUES ('GRENADA','GD');
INSERT INTO iso_codes(name,alpha2) VALUES ('GUADELOUPE','GP');
INSERT INTO iso_codes(name,alpha2) VALUES ('GUAM','GU');
INSERT INTO iso_codes(name,alpha2) VALUES ('GUATEMALA','GT');
INSERT INTO iso_codes(name,alpha2) VALUES ('GUERNSEY','GG');
INSERT INTO iso_codes(name,alpha2) VALUES ('GUINEA','GN');
INSERT INTO iso_codes(name,alpha2) VALUES ('GUINEA-BISSAU','GW');
INSERT INTO iso_codes(name,alpha2) VALUES ('GUYANA','GY');
INSERT INTO iso_codes(name,alpha2) VALUES ('HAITI','HT');
INSERT INTO iso_codes(name,alpha2) VALUES ('HEARD ISLAND AND MCDONALD ISLANDS','HM');
INSERT INTO iso_codes(name,alpha2) VALUES ('HOLY SEE (VATICAN CITY STATE)','VA');
INSERT INTO iso_codes(name,alpha2) VALUES ('HONDURAS','HN');
INSERT INTO iso_codes(name,alpha2) VALUES ('HONG KONG','HK');
INSERT INTO iso_codes(name,alpha2) VALUES ('HUNGARY','HU');
INSERT INTO iso_codes(name,alpha2) VALUES ('ICELAND','IS');
INSERT INTO iso_codes(name,alpha2) VALUES ('INDIA','IN');
INSERT INTO iso_codes(name,alpha2) VALUES ('INDONESIA','ID');
INSERT INTO iso_codes(name,alpha2) VALUES ('IRAN, ISLAMIC REPUBLIC OF','IR');
INSERT INTO iso_codes(name,alpha2) VALUES ('IRAQ','IQ');
INSERT INTO iso_codes(name,alpha2) VALUES ('IRELAND','IE');
INSERT INTO iso_codes(name,alpha2) VALUES ('ISLE OF MAN','IM');
INSERT INTO iso_codes(name,alpha2) VALUES ('ISRAEL','IL');
INSERT INTO iso_codes(name,alpha2) VALUES ('ITALY','IT');
INSERT INTO iso_codes(name,alpha2) VALUES ('JAMAICA','JM');
INSERT INTO iso_codes(name,alpha2) VALUES ('JAPAN','JP');
INSERT INTO iso_codes(name,alpha2) VALUES ('JERSEY','JE');
INSERT INTO iso_codes(name,alpha2) VALUES ('JORDAN','JO');
INSERT INTO iso_codes(name,alpha2) VALUES ('KAZAKHSTAN','KZ');
INSERT INTO iso_codes(name,alpha2) VALUES ('KENYA','KE');
INSERT INTO iso_codes(name,alpha2) VALUES ('KIRIBATI','KI');
INSERT INTO iso_codes(name,alpha2) VALUES ('KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF','KP');
INSERT INTO iso_codes(name,alpha2) VALUES ('KOREA, REPUBLIC OF','KR');
INSERT INTO iso_codes(name,alpha2) VALUES ('KUWAIT','KW');
INSERT INTO iso_codes(name,alpha2) VALUES ('KYRGYZSTAN','KG');
INSERT INTO iso_codes(name,alpha2) VALUES ('LAO PEOPLE\'S DEMOCRATIC REPUBLIC','LA');
INSERT INTO iso_codes(name,alpha2) VALUES ('LATVIA','LV');
INSERT INTO iso_codes(name,alpha2) VALUES ('LEBANON','LB');
INSERT INTO iso_codes(name,alpha2) VALUES ('LESOTHO','LS');
INSERT INTO iso_codes(name,alpha2) VALUES ('LIBERIA','LR');
INSERT INTO iso_codes(name,alpha2) VALUES ('LIBYA','LY');
INSERT INTO iso_codes(name,alpha2) VALUES ('LIECHTENSTEIN','LI');
INSERT INTO iso_codes(name,alpha2) VALUES ('LITHUANIA','LT');
INSERT INTO iso_codes(name,alpha2) VALUES ('LUXEMBOURG','LU');
INSERT INTO iso_codes(name,alpha2) VALUES ('MACAO','MO');
INSERT INTO iso_codes(name,alpha2) VALUES ('MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','MK');
INSERT INTO iso_codes(name,alpha2) VALUES ('MADAGASCAR','MG');
INSERT INTO iso_codes(name,alpha2) VALUES ('MALAWI','MW');
INSERT INTO iso_codes(name,alpha2) VALUES ('MALAYSIA','MY');
INSERT INTO iso_codes(name,alpha2) VALUES ('MALDIVES','MV');
INSERT INTO iso_codes(name,alpha2) VALUES ('MALI','ML');
INSERT INTO iso_codes(name,alpha2) VALUES ('MALTA','MT');
INSERT INTO iso_codes(name,alpha2) VALUES ('MARSHALL ISLANDS','MH');
INSERT INTO iso_codes(name,alpha2) VALUES ('MARTINIQUE','MQ');
INSERT INTO iso_codes(name,alpha2) VALUES ('MAURITANIA','MR');
INSERT INTO iso_codes(name,alpha2) VALUES ('MAURITIUS','MU');
INSERT INTO iso_codes(name,alpha2) VALUES ('MAYOTTE','YT');
INSERT INTO iso_codes(name,alpha2) VALUES ('MEXICO','MX');
INSERT INTO iso_codes(name,alpha2) VALUES ('MICRONESIA, FEDERATED STATES OF','FM');
INSERT INTO iso_codes(name,alpha2) VALUES ('MOLDOVA, REPUBLIC OF','MD');
INSERT INTO iso_codes(name,alpha2) VALUES ('MONACO','MC');
INSERT INTO iso_codes(name,alpha2) VALUES ('MONGOLIA','MN');
INSERT INTO iso_codes(name,alpha2) VALUES ('MONTENEGRO','ME');
INSERT INTO iso_codes(name,alpha2) VALUES ('MONTSERRAT','MS');
INSERT INTO iso_codes(name,alpha2) VALUES ('MOROCCO','MA');
INSERT INTO iso_codes(name,alpha2) VALUES ('MOZAMBIQUE','MZ');
INSERT INTO iso_codes(name,alpha2) VALUES ('MYANMAR','MM');
INSERT INTO iso_codes(name,alpha2) VALUES ('NAMIBIA','NA');
INSERT INTO iso_codes(name,alpha2) VALUES ('NAURU','NR');
INSERT INTO iso_codes(name,alpha2) VALUES ('NEPAL','NP');
INSERT INTO iso_codes(name,alpha2) VALUES ('NETHERLANDS','NL');
INSERT INTO iso_codes(name,alpha2) VALUES ('NEW CALEDONIA','NC');
INSERT INTO iso_codes(name,alpha2) VALUES ('NEW ZEALAND','NZ');
INSERT INTO iso_codes(name,alpha2) VALUES ('NICARAGUA','NI');
INSERT INTO iso_codes(name,alpha2) VALUES ('NIGER','NE');
INSERT INTO iso_codes(name,alpha2) VALUES ('NIGERIA','NG');
INSERT INTO iso_codes(name,alpha2) VALUES ('NIUE','NU');
INSERT INTO iso_codes(name,alpha2) VALUES ('NORFOLK ISLAND','NF');
INSERT INTO iso_codes(name,alpha2) VALUES ('NORTHERN MARIANA ISLANDS','MP');
INSERT INTO iso_codes(name,alpha2) VALUES ('NORWAY','NO');
INSERT INTO iso_codes(name,alpha2) VALUES ('OMAN','OM');
INSERT INTO iso_codes(name,alpha2) VALUES ('PAKISTAN','PK');
INSERT INTO iso_codes(name,alpha2) VALUES ('PALAU','PW');
INSERT INTO iso_codes(name,alpha2) VALUES ('PALESTINE, STATE OF','PS');
INSERT INTO iso_codes(name,alpha2) VALUES ('PANAMA','PA');
INSERT INTO iso_codes(name,alpha2) VALUES ('PAPUA NEW GUINEA','PG');
INSERT INTO iso_codes(name,alpha2) VALUES ('PARAGUAY','PY');
INSERT INTO iso_codes(name,alpha2) VALUES ('PERU','PE');
INSERT INTO iso_codes(name,alpha2) VALUES ('PHILIPPINES','PH');
INSERT INTO iso_codes(name,alpha2) VALUES ('PITCAIRN','PN');
INSERT INTO iso_codes(name,alpha2) VALUES ('POLAND','PL');
INSERT INTO iso_codes(name,alpha2) VALUES ('PORTUGAL','PT');
INSERT INTO iso_codes(name,alpha2) VALUES ('PUERTO RICO','PR');
INSERT INTO iso_codes(name,alpha2) VALUES ('QATAR','QA');
INSERT INTO iso_codes(name,alpha2) VALUES ('RÃ?UNION','RE');
INSERT INTO iso_codes(name,alpha2) VALUES ('ROMANIA','RO');
INSERT INTO iso_codes(name,alpha2) VALUES ('RUSSIAN FEDERATION','RU');
INSERT INTO iso_codes(name,alpha2) VALUES ('RWANDA','RW');
INSERT INTO iso_codes(name,alpha2) VALUES ('SAINT BARTHÃ?LEMY','BL');
INSERT INTO iso_codes(name,alpha2) VALUES ('SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA','SH');
INSERT INTO iso_codes(name,alpha2) VALUES ('SAINT KITTS AND NEVIS','KN');
INSERT INTO iso_codes(name,alpha2) VALUES ('SAINT LUCIA','LC');
INSERT INTO iso_codes(name,alpha2) VALUES ('SAINT MARTIN (FRENCH PART)','MF');
INSERT INTO iso_codes(name,alpha2) VALUES ('SAINT PIERRE AND MIQUELON','PM');
INSERT INTO iso_codes(name,alpha2) VALUES ('SAINT VINCENT AND THE GRENADINES','VC');
INSERT INTO iso_codes(name,alpha2) VALUES ('SAMOA','WS');
INSERT INTO iso_codes(name,alpha2) VALUES ('SAN MARINO','SM');
INSERT INTO iso_codes(name,alpha2) VALUES ('SAO TOME AND PRINCIPE','ST');
INSERT INTO iso_codes(name,alpha2) VALUES ('SAUDI ARABIA','SA');
INSERT INTO iso_codes(name,alpha2) VALUES ('SENEGAL','SN');
INSERT INTO iso_codes(name,alpha2) VALUES ('SERBIA','RS');
INSERT INTO iso_codes(name,alpha2) VALUES ('SEYCHELLES','SC');
INSERT INTO iso_codes(name,alpha2) VALUES ('SIERRA LEONE','SL');
INSERT INTO iso_codes(name,alpha2) VALUES ('SINGAPORE','SG');
INSERT INTO iso_codes(name,alpha2) VALUES ('SINT MAARTEN (DUTCH PART)','SX');
INSERT INTO iso_codes(name,alpha2) VALUES ('SLOVAKIA','SK');
INSERT INTO iso_codes(name,alpha2) VALUES ('SLOVENIA','SI');
INSERT INTO iso_codes(name,alpha2) VALUES ('SOLOMON ISLANDS','SB');
INSERT INTO iso_codes(name,alpha2) VALUES ('SOMALIA','SO');
INSERT INTO iso_codes(name,alpha2) VALUES ('SOUTH AFRICA','ZA');
INSERT INTO iso_codes(name,alpha2) VALUES ('SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','GS');
INSERT INTO iso_codes(name,alpha2) VALUES ('SOUTH SUDAN','SS');
INSERT INTO iso_codes(name,alpha2) VALUES ('SPAIN','ES');
INSERT INTO iso_codes(name,alpha2) VALUES ('SRI LANKA','LK');
INSERT INTO iso_codes(name,alpha2) VALUES ('SUDAN','SD');
INSERT INTO iso_codes(name,alpha2) VALUES ('SURINAME','SR');
INSERT INTO iso_codes(name,alpha2) VALUES ('SVALBARD AND JAN MAYEN','SJ');
INSERT INTO iso_codes(name,alpha2) VALUES ('SWAZILAND','SZ');
INSERT INTO iso_codes(name,alpha2) VALUES ('SWEDEN','SE');
INSERT INTO iso_codes(name,alpha2) VALUES ('SWITZERLAND','CH');
INSERT INTO iso_codes(name,alpha2) VALUES ('SYRIAN ARAB REPUBLIC','SY');
INSERT INTO iso_codes(name,alpha2) VALUES ('TAIWAN, PROVINCE OF CHINA','TW');
INSERT INTO iso_codes(name,alpha2) VALUES ('TAJIKISTAN','TJ');
INSERT INTO iso_codes(name,alpha2) VALUES ('TANZANIA, UNITED REPUBLIC OF','TZ');
INSERT INTO iso_codes(name,alpha2) VALUES ('THAILAND','TH');
INSERT INTO iso_codes(name,alpha2) VALUES ('TIMOR-LESTE','TL');
INSERT INTO iso_codes(name,alpha2) VALUES ('TOGO','TG');
INSERT INTO iso_codes(name,alpha2) VALUES ('TOKELAU','TK');
INSERT INTO iso_codes(name,alpha2) VALUES ('TONGA','TO');
INSERT INTO iso_codes(name,alpha2) VALUES ('TRINIDAD AND TOBAGO','TT');
INSERT INTO iso_codes(name,alpha2) VALUES ('TUNISIA','TN');
INSERT INTO iso_codes(name,alpha2) VALUES ('TURKEY','TR');
INSERT INTO iso_codes(name,alpha2) VALUES ('TURKMENISTAN','TM');
INSERT INTO iso_codes(name,alpha2) VALUES ('TURKS AND CAICOS ISLANDS','TC');
INSERT INTO iso_codes(name,alpha2) VALUES ('TUVALU','TV');
INSERT INTO iso_codes(name,alpha2) VALUES ('UGANDA','UG');
INSERT INTO iso_codes(name,alpha2) VALUES ('UKRAINE','UA');
INSERT INTO iso_codes(name,alpha2) VALUES ('UNITED ARAB EMIRATES','AE');
INSERT INTO iso_codes(name,alpha2) VALUES ('UNITED KINGDOM','GB');
INSERT INTO iso_codes(name,alpha2) VALUES ('UNITED STATES','US');
INSERT INTO iso_codes(name,alpha2) VALUES ('UNITED STATES MINOR OUTLYING ISLANDS','UM');
INSERT INTO iso_codes(name,alpha2) VALUES ('URUGUAY','UY');
INSERT INTO iso_codes(name,alpha2) VALUES ('UZBEKISTAN','UZ');
INSERT INTO iso_codes(name,alpha2) VALUES ('VANUATU','VU');
INSERT INTO iso_codes(name,alpha2) VALUES ('VENEZUELA, BOLIVARIAN REPUBLIC OF','VE');
INSERT INTO iso_codes(name,alpha2) VALUES ('VIET NAM','VN');
INSERT INTO iso_codes(name,alpha2) VALUES ('VIRGIN ISLANDS, BRITISH','VG');
INSERT INTO iso_codes(name,alpha2) VALUES ('VIRGIN ISLANDS, U.S.','VI');
INSERT INTO iso_codes(name,alpha2) VALUES ('WALLIS AND FUTUNA','WF');
INSERT INTO iso_codes(name,alpha2) VALUES ('WESTERN SAHARA','EH');
INSERT INTO iso_codes(name,alpha2) VALUES ('YEMEN','YE');
INSERT INTO iso_codes(name,alpha2) VALUES ('ZAMBIA','ZM');
INSERT INTO iso_codes(name,alpha2) VALUES ('ZIMBABWE','ZW');
